apiVersion: v1
description: High Performance Object Storage
name: minio
version: 5.4.0
appVersion: RELEASE.2024-12-18T13-15-44Z
keywords:
  - hanzo-s3
  - storage
  - object-storage
  - s3
  - cluster
home: https://hanzo.ai
icon: https://hanzo.ai/logo.png
sources:
- https://github.com/hanzoai/storage
maintainers:
- name: Hanzo AI, Inc
  email: dev@hanzo.ai
